version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wallet-db
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - 54324:5432
    volumes:
      - ./data:/var/lib/postgresql/data
